image: node:20

pipelines:
  branches:
    main:
      - step:
          name: "Check for Version Change in lerna.json"
          caches:
            - node
          script:
            - git fetch --all
            - git checkout main
            - git pull origin main
            - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
            - yarn install
            - yarn global add lerna
            - yarn build-ci:all
            - yarn lerna publish from-package --no-private --yes --loglevel debug
