image: node:20

pipelines:
  branches:
    main:
      - step:
          name: "Check for Version Change in lerna.json"
          caches:
            - node
          script:
            - git fetch --all
            - git checkout main
            - git pull origin main
            - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
            # Check if lerna.json has changed
            - |
              if git diff --name-only HEAD~1..HEAD | grep -q "lerna.json"; then
                echo "lerna.json changed, proceeding with publish"
                yarn install
                yarn global add lerna
                yarn build:all-ci
                yarn lerna publish from-package --no-private --yes --loglevel debug
              else
                echo "No changes to lerna.json, skipping publish"
                exit 0  # Exit early to prevent further steps
              fi
