'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SearchcraftAutoSearchForm as SearchcraftAutoSearchFormElement, defineCustomElement as defineSearchcraftAutoSearchForm } from "@searchcraft/javascript-sdk/dist/components/searchcraft-auto-search-form.js";
import { SearchcraftBaseSearchForm as SearchcraftBaseSearchFormElement, defineCustomElement as defineSearchcraftBaseSearchForm } from "@searchcraft/javascript-sdk/dist/components/searchcraft-base-search-form.js";
import { SearchcraftBaseSearchResult as SearchcraftBaseSearchResultElement, defineCustomElement as defineSearchcraftBaseSearchResult } from "@searchcraft/javascript-sdk/dist/components/searchcraft-base-search-result.js";
import { SearchcraftBaseSearchResults as SearchcraftBaseSearchResultsElement, defineCustomElement as defineSearchcraftBaseSearchResults } from "@searchcraft/javascript-sdk/dist/components/searchcraft-base-search-results.js";
import { SearchcraftButtonIcon as SearchcraftButtonIconElement, defineCustomElement as defineSearchcraftButtonIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-button-icon.js";
import { SearchcraftButton as SearchcraftButtonElement, defineCustomElement as defineSearchcraftButton } from "@searchcraft/javascript-sdk/dist/components/searchcraft-button.js";
import { SearchcraftCheckIcon as SearchcraftCheckIconElement, defineCustomElement as defineSearchcraftCheckIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-check-icon.js";
import { SearchcraftClearIconSet as SearchcraftClearIconSetElement, defineCustomElement as defineSearchcraftClearIconSet } from "@searchcraft/javascript-sdk/dist/components/searchcraft-clear-icon-set.js";
import { SearchcraftDashIcon as SearchcraftDashIconElement, defineCustomElement as defineSearchcraftDashIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-dash-icon.js";
import { SearchcraftErrorMessage as SearchcraftErrorMessageElement, defineCustomElement as defineSearchcraftErrorMessage } from "@searchcraft/javascript-sdk/dist/components/searchcraft-error-message.js";
import { SearchcraftFacetList as SearchcraftFacetListElement, defineCustomElement as defineSearchcraftFacetList } from "@searchcraft/javascript-sdk/dist/components/searchcraft-facet-list.js";
import { SearchcraftFilterPanel as SearchcraftFilterPanelElement, defineCustomElement as defineSearchcraftFilterPanel } from "@searchcraft/javascript-sdk/dist/components/searchcraft-filter-panel.js";
import { SearchcraftInputLabel as SearchcraftInputLabelElement, defineCustomElement as defineSearchcraftInputLabel } from "@searchcraft/javascript-sdk/dist/components/searchcraft-input-label.js";
import { SearchcraftInput as SearchcraftInputElement, defineCustomElement as defineSearchcraftInput } from "@searchcraft/javascript-sdk/dist/components/searchcraft-input.js";
import { SearchcraftResultsInfo as SearchcraftResultsInfoElement, defineCustomElement as defineSearchcraftResultsInfo } from "@searchcraft/javascript-sdk/dist/components/searchcraft-results-info.js";
import { SearchcraftSearchIconSet as SearchcraftSearchIconSetElement, defineCustomElement as defineSearchcraftSearchIconSet } from "@searchcraft/javascript-sdk/dist/components/searchcraft-search-icon-set.js";
import { SearchcraftSlider as SearchcraftSliderElement, defineCustomElement as defineSearchcraftSlider } from "@searchcraft/javascript-sdk/dist/components/searchcraft-slider.js";
import { SearchcraftSpinnerDark as SearchcraftSpinnerDarkElement, defineCustomElement as defineSearchcraftSpinnerDark } from "@searchcraft/javascript-sdk/dist/components/searchcraft-spinner-dark.js";
import { SearchcraftSpinnerLight as SearchcraftSpinnerLightElement, defineCustomElement as defineSearchcraftSpinnerLight } from "@searchcraft/javascript-sdk/dist/components/searchcraft-spinner-light.js";
import { SearchcraftToggleButton as SearchcraftToggleButtonElement, defineCustomElement as defineSearchcraftToggleButton } from "@searchcraft/javascript-sdk/dist/components/searchcraft-toggle-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type SearchcraftAutoSearchFormEvents = {
    onInputClearedOrNoResults: EventName<CustomEvent<void>>,
    onQuerySubmit: EventName<CustomEvent<string>>
};

export const SearchcraftAutoSearchForm: StencilReactComponent<SearchcraftAutoSearchFormElement, SearchcraftAutoSearchFormEvents> = /*@__PURE__*/ createComponent<SearchcraftAutoSearchFormElement, SearchcraftAutoSearchFormEvents>({
    tagName: 'searchcraft-auto-search-form',
    elementClass: SearchcraftAutoSearchFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputClearedOrNoResults: 'inputClearedOrNoResults',
        onQuerySubmit: 'querySubmit'
    } as SearchcraftAutoSearchFormEvents,
    defineCustomElement: defineSearchcraftAutoSearchForm
});

type SearchcraftBaseSearchFormEvents = { onClearInput: EventName<CustomEvent<any>> };

export const SearchcraftBaseSearchForm: StencilReactComponent<SearchcraftBaseSearchFormElement, SearchcraftBaseSearchFormEvents> = /*@__PURE__*/ createComponent<SearchcraftBaseSearchFormElement, SearchcraftBaseSearchFormEvents>({
    tagName: 'searchcraft-base-search-form',
    elementClass: SearchcraftBaseSearchFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onClearInput: 'clearInput' } as SearchcraftBaseSearchFormEvents,
    defineCustomElement: defineSearchcraftBaseSearchForm
});

type SearchcraftBaseSearchResultEvents = NonNullable<unknown>;

export const SearchcraftBaseSearchResult: StencilReactComponent<SearchcraftBaseSearchResultElement, SearchcraftBaseSearchResultEvents> = /*@__PURE__*/ createComponent<SearchcraftBaseSearchResultElement, SearchcraftBaseSearchResultEvents>({
    tagName: 'searchcraft-base-search-result',
    elementClass: SearchcraftBaseSearchResultElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftBaseSearchResultEvents,
    defineCustomElement: defineSearchcraftBaseSearchResult
});

type SearchcraftBaseSearchResultsEvents = { onNoResults: EventName<CustomEvent<void>> };

export const SearchcraftBaseSearchResults: StencilReactComponent<SearchcraftBaseSearchResultsElement, SearchcraftBaseSearchResultsEvents> = /*@__PURE__*/ createComponent<SearchcraftBaseSearchResultsElement, SearchcraftBaseSearchResultsEvents>({
    tagName: 'searchcraft-base-search-results',
    elementClass: SearchcraftBaseSearchResultsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onNoResults: 'noResults' } as SearchcraftBaseSearchResultsEvents,
    defineCustomElement: defineSearchcraftBaseSearchResults
});

type SearchcraftButtonEvents = { onButtonClick: EventName<CustomEvent<void>> };

export const SearchcraftButton: StencilReactComponent<SearchcraftButtonElement, SearchcraftButtonEvents> = /*@__PURE__*/ createComponent<SearchcraftButtonElement, SearchcraftButtonEvents>({
    tagName: 'searchcraft-button',
    elementClass: SearchcraftButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonClick: 'buttonClick' } as SearchcraftButtonEvents,
    defineCustomElement: defineSearchcraftButton
});

type SearchcraftButtonIconEvents = NonNullable<unknown>;

export const SearchcraftButtonIcon: StencilReactComponent<SearchcraftButtonIconElement, SearchcraftButtonIconEvents> = /*@__PURE__*/ createComponent<SearchcraftButtonIconElement, SearchcraftButtonIconEvents>({
    tagName: 'searchcraft-button-icon',
    elementClass: SearchcraftButtonIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftButtonIconEvents,
    defineCustomElement: defineSearchcraftButtonIcon
});

type SearchcraftCheckIconEvents = NonNullable<unknown>;

export const SearchcraftCheckIcon: StencilReactComponent<SearchcraftCheckIconElement, SearchcraftCheckIconEvents> = /*@__PURE__*/ createComponent<SearchcraftCheckIconElement, SearchcraftCheckIconEvents>({
    tagName: 'searchcraft-check-icon',
    elementClass: SearchcraftCheckIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftCheckIconEvents,
    defineCustomElement: defineSearchcraftCheckIcon
});

type SearchcraftClearIconSetEvents = NonNullable<unknown>;

export const SearchcraftClearIconSet: StencilReactComponent<SearchcraftClearIconSetElement, SearchcraftClearIconSetEvents> = /*@__PURE__*/ createComponent<SearchcraftClearIconSetElement, SearchcraftClearIconSetEvents>({
    tagName: 'searchcraft-clear-icon-set',
    elementClass: SearchcraftClearIconSetElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftClearIconSetEvents,
    defineCustomElement: defineSearchcraftClearIconSet
});

type SearchcraftDashIconEvents = NonNullable<unknown>;

export const SearchcraftDashIcon: StencilReactComponent<SearchcraftDashIconElement, SearchcraftDashIconEvents> = /*@__PURE__*/ createComponent<SearchcraftDashIconElement, SearchcraftDashIconEvents>({
    tagName: 'searchcraft-dash-icon',
    elementClass: SearchcraftDashIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftDashIconEvents,
    defineCustomElement: defineSearchcraftDashIcon
});

type SearchcraftErrorMessageEvents = NonNullable<unknown>;

export const SearchcraftErrorMessage: StencilReactComponent<SearchcraftErrorMessageElement, SearchcraftErrorMessageEvents> = /*@__PURE__*/ createComponent<SearchcraftErrorMessageElement, SearchcraftErrorMessageEvents>({
    tagName: 'searchcraft-error-message',
    elementClass: SearchcraftErrorMessageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftErrorMessageEvents,
    defineCustomElement: defineSearchcraftErrorMessage
});

type SearchcraftFacetListEvents = { onFacetSelectionUpdated: EventName<CustomEvent<{ paths: string[] }>> };

export const SearchcraftFacetList: StencilReactComponent<SearchcraftFacetListElement, SearchcraftFacetListEvents> = /*@__PURE__*/ createComponent<SearchcraftFacetListElement, SearchcraftFacetListEvents>({
    tagName: 'searchcraft-facet-list',
    elementClass: SearchcraftFacetListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFacetSelectionUpdated: 'facetSelectionUpdated' } as SearchcraftFacetListEvents,
    defineCustomElement: defineSearchcraftFacetList
});

type SearchcraftFilterPanelEvents = NonNullable<unknown>;

export const SearchcraftFilterPanel: StencilReactComponent<SearchcraftFilterPanelElement, SearchcraftFilterPanelEvents> = /*@__PURE__*/ createComponent<SearchcraftFilterPanelElement, SearchcraftFilterPanelEvents>({
    tagName: 'searchcraft-filter-panel',
    elementClass: SearchcraftFilterPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftFilterPanelEvents,
    defineCustomElement: defineSearchcraftFilterPanel
});

type SearchcraftInputEvents = {
    onClearInput: EventName<CustomEvent<void>>,
    onInputChange: EventName<CustomEvent<string>>
};

export const SearchcraftInput: StencilReactComponent<SearchcraftInputElement, SearchcraftInputEvents> = /*@__PURE__*/ createComponent<SearchcraftInputElement, SearchcraftInputEvents>({
    tagName: 'searchcraft-input',
    elementClass: SearchcraftInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onClearInput: 'clearInput',
        onInputChange: 'inputChange'
    } as SearchcraftInputEvents,
    defineCustomElement: defineSearchcraftInput
});

type SearchcraftInputLabelEvents = NonNullable<unknown>;

export const SearchcraftInputLabel: StencilReactComponent<SearchcraftInputLabelElement, SearchcraftInputLabelEvents> = /*@__PURE__*/ createComponent<SearchcraftInputLabelElement, SearchcraftInputLabelEvents>({
    tagName: 'searchcraft-input-label',
    elementClass: SearchcraftInputLabelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftInputLabelEvents,
    defineCustomElement: defineSearchcraftInputLabel
});

type SearchcraftResultsInfoEvents = NonNullable<unknown>;

export const SearchcraftResultsInfo: StencilReactComponent<SearchcraftResultsInfoElement, SearchcraftResultsInfoEvents> = /*@__PURE__*/ createComponent<SearchcraftResultsInfoElement, SearchcraftResultsInfoEvents>({
    tagName: 'searchcraft-results-info',
    elementClass: SearchcraftResultsInfoElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftResultsInfoEvents,
    defineCustomElement: defineSearchcraftResultsInfo
});

type SearchcraftSearchIconSetEvents = NonNullable<unknown>;

export const SearchcraftSearchIconSet: StencilReactComponent<SearchcraftSearchIconSetElement, SearchcraftSearchIconSetEvents> = /*@__PURE__*/ createComponent<SearchcraftSearchIconSetElement, SearchcraftSearchIconSetEvents>({
    tagName: 'searchcraft-search-icon-set',
    elementClass: SearchcraftSearchIconSetElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftSearchIconSetEvents,
    defineCustomElement: defineSearchcraftSearchIconSet
});

type SearchcraftSliderEvents = { onRangeChanged: EventName<CustomEvent<{ startValue: number; endValue: number }>> };

export const SearchcraftSlider: StencilReactComponent<SearchcraftSliderElement, SearchcraftSliderEvents> = /*@__PURE__*/ createComponent<SearchcraftSliderElement, SearchcraftSliderEvents>({
    tagName: 'searchcraft-slider',
    elementClass: SearchcraftSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onRangeChanged: 'rangeChanged' } as SearchcraftSliderEvents,
    defineCustomElement: defineSearchcraftSlider
});

type SearchcraftSpinnerDarkEvents = NonNullable<unknown>;

export const SearchcraftSpinnerDark: StencilReactComponent<SearchcraftSpinnerDarkElement, SearchcraftSpinnerDarkEvents> = /*@__PURE__*/ createComponent<SearchcraftSpinnerDarkElement, SearchcraftSpinnerDarkEvents>({
    tagName: 'searchcraft-spinner-dark',
    elementClass: SearchcraftSpinnerDarkElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftSpinnerDarkEvents,
    defineCustomElement: defineSearchcraftSpinnerDark
});

type SearchcraftSpinnerLightEvents = NonNullable<unknown>;

export const SearchcraftSpinnerLight: StencilReactComponent<SearchcraftSpinnerLightElement, SearchcraftSpinnerLightEvents> = /*@__PURE__*/ createComponent<SearchcraftSpinnerLightElement, SearchcraftSpinnerLightEvents>({
    tagName: 'searchcraft-spinner-light',
    elementClass: SearchcraftSpinnerLightElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftSpinnerLightEvents,
    defineCustomElement: defineSearchcraftSpinnerLight
});

type SearchcraftToggleButtonEvents = { onToggleUpdated: EventName<CustomEvent<boolean>> };

export const SearchcraftToggleButton: StencilReactComponent<SearchcraftToggleButtonElement, SearchcraftToggleButtonEvents> = /*@__PURE__*/ createComponent<SearchcraftToggleButtonElement, SearchcraftToggleButtonEvents>({
    tagName: 'searchcraft-toggle-button',
    elementClass: SearchcraftToggleButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onToggleUpdated: 'toggleUpdated' } as SearchcraftToggleButtonEvents,
    defineCustomElement: defineSearchcraftToggleButton
});
