'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SearchcraftBaseSearchResult as SearchcraftBaseSearchResultElement, defineCustomElement as defineSearchcraftBaseSearchResult } from "@searchcraft/javascript-sdk/dist/components/searchcraft-base-search-result.js";
import { SearchcraftBaseSearchResults as SearchcraftBaseSearchResultsElement, defineCustomElement as defineSearchcraftBaseSearchResults } from "@searchcraft/javascript-sdk/dist/components/searchcraft-base-search-results.js";
import { SearchcraftButtonIcon as SearchcraftButtonIconElement, defineCustomElement as defineSearchcraftButtonIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-button-icon.js";
import { SearchcraftButton as SearchcraftButtonElement, defineCustomElement as defineSearchcraftButton } from "@searchcraft/javascript-sdk/dist/components/searchcraft-button.js";
import { SearchcraftCheckIcon as SearchcraftCheckIconElement, defineCustomElement as defineSearchcraftCheckIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-check-icon.js";
import { SearchcraftClearIconSet as SearchcraftClearIconSetElement, defineCustomElement as defineSearchcraftClearIconSet } from "@searchcraft/javascript-sdk/dist/components/searchcraft-clear-icon-set.js";
import { SearchcraftDashIcon as SearchcraftDashIconElement, defineCustomElement as defineSearchcraftDashIcon } from "@searchcraft/javascript-sdk/dist/components/searchcraft-dash-icon.js";
import { SearchcraftErrorMessage as SearchcraftErrorMessageElement, defineCustomElement as defineSearchcraftErrorMessage } from "@searchcraft/javascript-sdk/dist/components/searchcraft-error-message.js";
import { SearchcraftFacetList as SearchcraftFacetListElement, defineCustomElement as defineSearchcraftFacetList } from "@searchcraft/javascript-sdk/dist/components/searchcraft-facet-list.js";
import { SearchcraftFilterPanel as SearchcraftFilterPanelElement, defineCustomElement as defineSearchcraftFilterPanel } from "@searchcraft/javascript-sdk/dist/components/searchcraft-filter-panel.js";
import { SearchcraftInputForm as SearchcraftInputFormElement, defineCustomElement as defineSearchcraftInputForm } from "@searchcraft/javascript-sdk/dist/components/searchcraft-input-form.js";
import { SearchcraftInputLabel as SearchcraftInputLabelElement, defineCustomElement as defineSearchcraftInputLabel } from "@searchcraft/javascript-sdk/dist/components/searchcraft-input-label.js";
import { SearchcraftPopoverForm as SearchcraftPopoverFormElement, defineCustomElement as defineSearchcraftPopoverForm } from "@searchcraft/javascript-sdk/dist/components/searchcraft-popover-form.js";
import { SearchcraftPopoverListView as SearchcraftPopoverListViewElement, defineCustomElement as defineSearchcraftPopoverListView } from "@searchcraft/javascript-sdk/dist/components/searchcraft-popover-list-view.js";
import { SearchcraftPopoverResult as SearchcraftPopoverResultElement, defineCustomElement as defineSearchcraftPopoverResult } from "@searchcraft/javascript-sdk/dist/components/searchcraft-popover-result.js";
import { SearchcraftResultsInfo as SearchcraftResultsInfoElement, defineCustomElement as defineSearchcraftResultsInfo } from "@searchcraft/javascript-sdk/dist/components/searchcraft-results-info.js";
import { SearchcraftSearchIconSet as SearchcraftSearchIconSetElement, defineCustomElement as defineSearchcraftSearchIconSet } from "@searchcraft/javascript-sdk/dist/components/searchcraft-search-icon-set.js";
import { SearchcraftSlider as SearchcraftSliderElement, defineCustomElement as defineSearchcraftSlider } from "@searchcraft/javascript-sdk/dist/components/searchcraft-slider.js";
import { SearchcraftToggleButton as SearchcraftToggleButtonElement, defineCustomElement as defineSearchcraftToggleButton } from "@searchcraft/javascript-sdk/dist/components/searchcraft-toggle-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type SearchcraftBaseSearchResultEvents = NonNullable<unknown>;

export const SearchcraftBaseSearchResult: StencilReactComponent<SearchcraftBaseSearchResultElement, SearchcraftBaseSearchResultEvents> = /*@__PURE__*/ createComponent<SearchcraftBaseSearchResultElement, SearchcraftBaseSearchResultEvents>({
    tagName: 'searchcraft-base-search-result',
    elementClass: SearchcraftBaseSearchResultElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftBaseSearchResultEvents,
    defineCustomElement: defineSearchcraftBaseSearchResult
});

type SearchcraftBaseSearchResultsEvents = { onNoResults: EventName<CustomEvent<void>> };

export const SearchcraftBaseSearchResults: StencilReactComponent<SearchcraftBaseSearchResultsElement, SearchcraftBaseSearchResultsEvents> = /*@__PURE__*/ createComponent<SearchcraftBaseSearchResultsElement, SearchcraftBaseSearchResultsEvents>({
    tagName: 'searchcraft-base-search-results',
    elementClass: SearchcraftBaseSearchResultsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onNoResults: 'noResults' } as SearchcraftBaseSearchResultsEvents,
    defineCustomElement: defineSearchcraftBaseSearchResults
});

type SearchcraftButtonEvents = { onButtonClick: EventName<CustomEvent<void>> };

export const SearchcraftButton: StencilReactComponent<SearchcraftButtonElement, SearchcraftButtonEvents> = /*@__PURE__*/ createComponent<SearchcraftButtonElement, SearchcraftButtonEvents>({
    tagName: 'searchcraft-button',
    elementClass: SearchcraftButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonClick: 'buttonClick' } as SearchcraftButtonEvents,
    defineCustomElement: defineSearchcraftButton
});

type SearchcraftButtonIconEvents = NonNullable<unknown>;

export const SearchcraftButtonIcon: StencilReactComponent<SearchcraftButtonIconElement, SearchcraftButtonIconEvents> = /*@__PURE__*/ createComponent<SearchcraftButtonIconElement, SearchcraftButtonIconEvents>({
    tagName: 'searchcraft-button-icon',
    elementClass: SearchcraftButtonIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftButtonIconEvents,
    defineCustomElement: defineSearchcraftButtonIcon
});

type SearchcraftCheckIconEvents = NonNullable<unknown>;

export const SearchcraftCheckIcon: StencilReactComponent<SearchcraftCheckIconElement, SearchcraftCheckIconEvents> = /*@__PURE__*/ createComponent<SearchcraftCheckIconElement, SearchcraftCheckIconEvents>({
    tagName: 'searchcraft-check-icon',
    elementClass: SearchcraftCheckIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftCheckIconEvents,
    defineCustomElement: defineSearchcraftCheckIcon
});

type SearchcraftClearIconSetEvents = NonNullable<unknown>;

export const SearchcraftClearIconSet: StencilReactComponent<SearchcraftClearIconSetElement, SearchcraftClearIconSetEvents> = /*@__PURE__*/ createComponent<SearchcraftClearIconSetElement, SearchcraftClearIconSetEvents>({
    tagName: 'searchcraft-clear-icon-set',
    elementClass: SearchcraftClearIconSetElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftClearIconSetEvents,
    defineCustomElement: defineSearchcraftClearIconSet
});

type SearchcraftDashIconEvents = NonNullable<unknown>;

export const SearchcraftDashIcon: StencilReactComponent<SearchcraftDashIconElement, SearchcraftDashIconEvents> = /*@__PURE__*/ createComponent<SearchcraftDashIconElement, SearchcraftDashIconEvents>({
    tagName: 'searchcraft-dash-icon',
    elementClass: SearchcraftDashIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftDashIconEvents,
    defineCustomElement: defineSearchcraftDashIcon
});

type SearchcraftErrorMessageEvents = NonNullable<unknown>;

export const SearchcraftErrorMessage: StencilReactComponent<SearchcraftErrorMessageElement, SearchcraftErrorMessageEvents> = /*@__PURE__*/ createComponent<SearchcraftErrorMessageElement, SearchcraftErrorMessageEvents>({
    tagName: 'searchcraft-error-message',
    elementClass: SearchcraftErrorMessageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftErrorMessageEvents,
    defineCustomElement: defineSearchcraftErrorMessage
});

type SearchcraftFacetListEvents = { onFacetSelectionUpdated: EventName<CustomEvent<{ paths: string[] }>> };

export const SearchcraftFacetList: StencilReactComponent<SearchcraftFacetListElement, SearchcraftFacetListEvents> = /*@__PURE__*/ createComponent<SearchcraftFacetListElement, SearchcraftFacetListEvents>({
    tagName: 'searchcraft-facet-list',
    elementClass: SearchcraftFacetListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFacetSelectionUpdated: 'facetSelectionUpdated' } as SearchcraftFacetListEvents,
    defineCustomElement: defineSearchcraftFacetList
});

type SearchcraftFilterPanelEvents = NonNullable<unknown>;

export const SearchcraftFilterPanel: StencilReactComponent<SearchcraftFilterPanelElement, SearchcraftFilterPanelEvents> = /*@__PURE__*/ createComponent<SearchcraftFilterPanelElement, SearchcraftFilterPanelEvents>({
    tagName: 'searchcraft-filter-panel',
    elementClass: SearchcraftFilterPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftFilterPanelEvents,
    defineCustomElement: defineSearchcraftFilterPanel
});

type SearchcraftInputFormEvents = {
    onInputCleared: EventName<CustomEvent<void>>,
    onNoResultsReceived: EventName<CustomEvent<void>>,
    onInputFocus: EventName<CustomEvent<void>>,
    onInputBlur: EventName<CustomEvent<void>>
};

export const SearchcraftInputForm: StencilReactComponent<SearchcraftInputFormElement, SearchcraftInputFormEvents> = /*@__PURE__*/ createComponent<SearchcraftInputFormElement, SearchcraftInputFormEvents>({
    tagName: 'searchcraft-input-form',
    elementClass: SearchcraftInputFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onInputCleared: 'inputCleared',
        onNoResultsReceived: 'noResultsReceived',
        onInputFocus: 'inputFocus',
        onInputBlur: 'inputBlur'
    } as SearchcraftInputFormEvents,
    defineCustomElement: defineSearchcraftInputForm
});

type SearchcraftInputLabelEvents = NonNullable<unknown>;

export const SearchcraftInputLabel: StencilReactComponent<SearchcraftInputLabelElement, SearchcraftInputLabelEvents> = /*@__PURE__*/ createComponent<SearchcraftInputLabelElement, SearchcraftInputLabelEvents>({
    tagName: 'searchcraft-input-label',
    elementClass: SearchcraftInputLabelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftInputLabelEvents,
    defineCustomElement: defineSearchcraftInputLabel
});

type SearchcraftPopoverFormEvents = NonNullable<unknown>;

export const SearchcraftPopoverForm: StencilReactComponent<SearchcraftPopoverFormElement, SearchcraftPopoverFormEvents> = /*@__PURE__*/ createComponent<SearchcraftPopoverFormElement, SearchcraftPopoverFormEvents>({
    tagName: 'searchcraft-popover-form',
    elementClass: SearchcraftPopoverFormElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftPopoverFormEvents,
    defineCustomElement: defineSearchcraftPopoverForm
});

type SearchcraftPopoverListViewEvents = NonNullable<unknown>;

export const SearchcraftPopoverListView: StencilReactComponent<SearchcraftPopoverListViewElement, SearchcraftPopoverListViewEvents> = /*@__PURE__*/ createComponent<SearchcraftPopoverListViewElement, SearchcraftPopoverListViewEvents>({
    tagName: 'searchcraft-popover-list-view',
    elementClass: SearchcraftPopoverListViewElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftPopoverListViewEvents,
    defineCustomElement: defineSearchcraftPopoverListView
});

type SearchcraftPopoverResultEvents = NonNullable<unknown>;

export const SearchcraftPopoverResult: StencilReactComponent<SearchcraftPopoverResultElement, SearchcraftPopoverResultEvents> = /*@__PURE__*/ createComponent<SearchcraftPopoverResultElement, SearchcraftPopoverResultEvents>({
    tagName: 'searchcraft-popover-result',
    elementClass: SearchcraftPopoverResultElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftPopoverResultEvents,
    defineCustomElement: defineSearchcraftPopoverResult
});

type SearchcraftResultsInfoEvents = NonNullable<unknown>;

export const SearchcraftResultsInfo: StencilReactComponent<SearchcraftResultsInfoElement, SearchcraftResultsInfoEvents> = /*@__PURE__*/ createComponent<SearchcraftResultsInfoElement, SearchcraftResultsInfoEvents>({
    tagName: 'searchcraft-results-info',
    elementClass: SearchcraftResultsInfoElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftResultsInfoEvents,
    defineCustomElement: defineSearchcraftResultsInfo
});

type SearchcraftSearchIconSetEvents = NonNullable<unknown>;

export const SearchcraftSearchIconSet: StencilReactComponent<SearchcraftSearchIconSetElement, SearchcraftSearchIconSetEvents> = /*@__PURE__*/ createComponent<SearchcraftSearchIconSetElement, SearchcraftSearchIconSetEvents>({
    tagName: 'searchcraft-search-icon-set',
    elementClass: SearchcraftSearchIconSetElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchcraftSearchIconSetEvents,
    defineCustomElement: defineSearchcraftSearchIconSet
});

type SearchcraftSliderEvents = { onRangeChanged: EventName<CustomEvent<{ startValue: number; endValue: number }>> };

export const SearchcraftSlider: StencilReactComponent<SearchcraftSliderElement, SearchcraftSliderEvents> = /*@__PURE__*/ createComponent<SearchcraftSliderElement, SearchcraftSliderEvents>({
    tagName: 'searchcraft-slider',
    elementClass: SearchcraftSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onRangeChanged: 'rangeChanged' } as SearchcraftSliderEvents,
    defineCustomElement: defineSearchcraftSlider
});

type SearchcraftToggleButtonEvents = { onToggleUpdated: EventName<CustomEvent<boolean>> };

export const SearchcraftToggleButton: StencilReactComponent<SearchcraftToggleButtonElement, SearchcraftToggleButtonEvents> = /*@__PURE__*/ createComponent<SearchcraftToggleButtonElement, SearchcraftToggleButtonEvents>({
    tagName: 'searchcraft-toggle-button',
    elementClass: SearchcraftToggleButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onToggleUpdated: 'toggleUpdated' } as SearchcraftToggleButtonEvents,
    defineCustomElement: defineSearchcraftToggleButton
});
