/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SearchcraftConfig } from "@searchcraft/core";
export { SearchcraftConfig } from "@searchcraft/core";
export namespace Components {
    interface SearchcraftAutoSearchForm {
        "autoSearchFormClass": string;
        "clearInput": () => void;
        "config": SearchcraftConfig;
        "customStylesForInput": string | Record<string, string>;
        "inputCaptionValue": string;
        "labelForInput": string;
        "placeholderValue": string;
        "searchContainerClass": string;
    }
    interface SearchcraftBaseSearchForm {
        "buttonLabel": string;
        "buttonPlacement": 'right' | 'left';
        "config": SearchcraftConfig;
        "errorMessage": string;
        "inputLabel": string;
    }
    interface SearchcraftBaseSearchResult {
        "bodyContent": string | undefined;
        "buttonHref": string | undefined;
        "buttonLabel": string | undefined;
        "buttonRel": 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "buttonTarget": '_blank' | '_self' | '_top' | '_parent';
        "containerHref": string | undefined;
        "containerRel": 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "containerTarget": '_blank' | '_self' | '_top' | '_parent';
        "customStyles": string | undefined;
        "documentPosition": number;
        "footerContent": string | undefined;
        "imageAlt": string | undefined;
        "imagePlacement": 'left' | 'right';
        "imageSrc": string | undefined;
        "subtitleContent": string | undefined;
        "titleContent": string | undefined;
    }
    interface SearchcraftBaseSearchResults {
        "adInterval": number;
        "buttonLabel": string | undefined;
        "buttonRel": 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "buttonTarget": '_blank' | '_self' | '_top' | '_parent';
        "containerHref": string | undefined;
        "containerRel": 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "containerTarget": '_blank' | '_self' | '_top' | '_parent';
        "customStylesForResults": | string
    | Record<string, Record<string, string>>
    | undefined;
        "placeAdAtEnd": boolean;
        "placeAdAtStart": boolean;
        "resultImagePlacement": 'left' | 'right';
        "searchResultMappings": string | undefined;
    }
    interface SearchcraftButton {
        "iconElement"?: Element;
        "iconOnly": boolean;
        "iconPosition": string;
        "label": string;
    }
    interface SearchcraftButtonIcon {
    }
    interface SearchcraftCheckIcon {
    }
    interface SearchcraftClearIconSet {
        /**
          * Type of the icon to display. Options: 'clear-light', 'clear-dark', 'arrow-light', 'arrow-dark'
         */
        "type": 'clear-light' | 'clear-dark' | 'arrow-light' | 'arrow-dark';
    }
    interface SearchcraftDashIcon {
    }
    interface SearchcraftErrorMessage {
        "errorMessage"?: string;
    }
    interface SearchcraftFacetList {
        "fieldName": string;
    }
    interface SearchcraftFilterPanel {
        "items": string | undefined;
    }
    interface SearchcraftInput {
        "customStyles": string | Record<string, string>;
        "error": boolean;
        "flex": boolean;
        "inputCaptionClassName": string;
        "inputCaptionValue": string;
        "inputClassName": string;
        "isRequesting": boolean;
        "placeholderValue": string;
        "query": string;
    }
    interface SearchcraftInputLabel {
        "inputLabelClassName"?: string;
        "label"?: string;
    }
    interface SearchcraftResultsInfo {
    }
    interface SearchcraftSearchIconSet {
        "height": number;
        /**
          * Type of the icon to display. Options: 'search-light', 'search-dark', 'error-light', 'error-dark'
         */
        "type": 'search-light' | 'search-dark' | 'error-light' | 'error-dark';
        "width": number;
    }
    interface SearchcraftSlider {
        "dataType": 'number' | 'date';
        "granularity": number;
        "max": number;
        "min": number;
    }
    interface SearchcraftSpinnerDark {
    }
    interface SearchcraftSpinnerLight {
    }
    interface SearchcraftToggleButton {
        /**
          * Type of the toggle - determines what it controls 'mode': toggles between 'fuzzy' and 'normal' 'sort': toggles between 'asc' and 'desc'
         */
        "label": string;
        "subLabel": string | undefined;
    }
}
export interface SearchcraftAutoSearchFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftAutoSearchFormElement;
}
export interface SearchcraftBaseSearchFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftBaseSearchFormElement;
}
export interface SearchcraftBaseSearchResultsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftBaseSearchResultsElement;
}
export interface SearchcraftButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftButtonElement;
}
export interface SearchcraftFacetListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftFacetListElement;
}
export interface SearchcraftInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftInputElement;
}
export interface SearchcraftSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftSliderElement;
}
export interface SearchcraftToggleButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchcraftToggleButtonElement;
}
declare global {
    interface HTMLSearchcraftAutoSearchFormElementEventMap {
        "inputClearedOrNoResults": void;
        "querySubmit": string;
    }
    interface HTMLSearchcraftAutoSearchFormElement extends Components.SearchcraftAutoSearchForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftAutoSearchFormElementEventMap>(type: K, listener: (this: HTMLSearchcraftAutoSearchFormElement, ev: SearchcraftAutoSearchFormCustomEvent<HTMLSearchcraftAutoSearchFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftAutoSearchFormElementEventMap>(type: K, listener: (this: HTMLSearchcraftAutoSearchFormElement, ev: SearchcraftAutoSearchFormCustomEvent<HTMLSearchcraftAutoSearchFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftAutoSearchFormElement: {
        prototype: HTMLSearchcraftAutoSearchFormElement;
        new (): HTMLSearchcraftAutoSearchFormElement;
    };
    interface HTMLSearchcraftBaseSearchFormElementEventMap {
        "clearInput": any;
    }
    interface HTMLSearchcraftBaseSearchFormElement extends Components.SearchcraftBaseSearchForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftBaseSearchFormElementEventMap>(type: K, listener: (this: HTMLSearchcraftBaseSearchFormElement, ev: SearchcraftBaseSearchFormCustomEvent<HTMLSearchcraftBaseSearchFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftBaseSearchFormElementEventMap>(type: K, listener: (this: HTMLSearchcraftBaseSearchFormElement, ev: SearchcraftBaseSearchFormCustomEvent<HTMLSearchcraftBaseSearchFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftBaseSearchFormElement: {
        prototype: HTMLSearchcraftBaseSearchFormElement;
        new (): HTMLSearchcraftBaseSearchFormElement;
    };
    interface HTMLSearchcraftBaseSearchResultElement extends Components.SearchcraftBaseSearchResult, HTMLStencilElement {
    }
    var HTMLSearchcraftBaseSearchResultElement: {
        prototype: HTMLSearchcraftBaseSearchResultElement;
        new (): HTMLSearchcraftBaseSearchResultElement;
    };
    interface HTMLSearchcraftBaseSearchResultsElementEventMap {
        "noResults": void;
    }
    interface HTMLSearchcraftBaseSearchResultsElement extends Components.SearchcraftBaseSearchResults, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftBaseSearchResultsElementEventMap>(type: K, listener: (this: HTMLSearchcraftBaseSearchResultsElement, ev: SearchcraftBaseSearchResultsCustomEvent<HTMLSearchcraftBaseSearchResultsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftBaseSearchResultsElementEventMap>(type: K, listener: (this: HTMLSearchcraftBaseSearchResultsElement, ev: SearchcraftBaseSearchResultsCustomEvent<HTMLSearchcraftBaseSearchResultsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftBaseSearchResultsElement: {
        prototype: HTMLSearchcraftBaseSearchResultsElement;
        new (): HTMLSearchcraftBaseSearchResultsElement;
    };
    interface HTMLSearchcraftButtonElementEventMap {
        "buttonClick": void;
    }
    interface HTMLSearchcraftButtonElement extends Components.SearchcraftButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftButtonElementEventMap>(type: K, listener: (this: HTMLSearchcraftButtonElement, ev: SearchcraftButtonCustomEvent<HTMLSearchcraftButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftButtonElementEventMap>(type: K, listener: (this: HTMLSearchcraftButtonElement, ev: SearchcraftButtonCustomEvent<HTMLSearchcraftButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftButtonElement: {
        prototype: HTMLSearchcraftButtonElement;
        new (): HTMLSearchcraftButtonElement;
    };
    interface HTMLSearchcraftButtonIconElement extends Components.SearchcraftButtonIcon, HTMLStencilElement {
    }
    var HTMLSearchcraftButtonIconElement: {
        prototype: HTMLSearchcraftButtonIconElement;
        new (): HTMLSearchcraftButtonIconElement;
    };
    interface HTMLSearchcraftCheckIconElement extends Components.SearchcraftCheckIcon, HTMLStencilElement {
    }
    var HTMLSearchcraftCheckIconElement: {
        prototype: HTMLSearchcraftCheckIconElement;
        new (): HTMLSearchcraftCheckIconElement;
    };
    interface HTMLSearchcraftClearIconSetElement extends Components.SearchcraftClearIconSet, HTMLStencilElement {
    }
    var HTMLSearchcraftClearIconSetElement: {
        prototype: HTMLSearchcraftClearIconSetElement;
        new (): HTMLSearchcraftClearIconSetElement;
    };
    interface HTMLSearchcraftDashIconElement extends Components.SearchcraftDashIcon, HTMLStencilElement {
    }
    var HTMLSearchcraftDashIconElement: {
        prototype: HTMLSearchcraftDashIconElement;
        new (): HTMLSearchcraftDashIconElement;
    };
    interface HTMLSearchcraftErrorMessageElement extends Components.SearchcraftErrorMessage, HTMLStencilElement {
    }
    var HTMLSearchcraftErrorMessageElement: {
        prototype: HTMLSearchcraftErrorMessageElement;
        new (): HTMLSearchcraftErrorMessageElement;
    };
    interface HTMLSearchcraftFacetListElementEventMap {
        "facetSelectionUpdated": { paths: string[] };
    }
    interface HTMLSearchcraftFacetListElement extends Components.SearchcraftFacetList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftFacetListElementEventMap>(type: K, listener: (this: HTMLSearchcraftFacetListElement, ev: SearchcraftFacetListCustomEvent<HTMLSearchcraftFacetListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftFacetListElementEventMap>(type: K, listener: (this: HTMLSearchcraftFacetListElement, ev: SearchcraftFacetListCustomEvent<HTMLSearchcraftFacetListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftFacetListElement: {
        prototype: HTMLSearchcraftFacetListElement;
        new (): HTMLSearchcraftFacetListElement;
    };
    interface HTMLSearchcraftFilterPanelElement extends Components.SearchcraftFilterPanel, HTMLStencilElement {
    }
    var HTMLSearchcraftFilterPanelElement: {
        prototype: HTMLSearchcraftFilterPanelElement;
        new (): HTMLSearchcraftFilterPanelElement;
    };
    interface HTMLSearchcraftInputElementEventMap {
        "clearInput": void;
        "inputChange": string;
    }
    interface HTMLSearchcraftInputElement extends Components.SearchcraftInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftInputElementEventMap>(type: K, listener: (this: HTMLSearchcraftInputElement, ev: SearchcraftInputCustomEvent<HTMLSearchcraftInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftInputElementEventMap>(type: K, listener: (this: HTMLSearchcraftInputElement, ev: SearchcraftInputCustomEvent<HTMLSearchcraftInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftInputElement: {
        prototype: HTMLSearchcraftInputElement;
        new (): HTMLSearchcraftInputElement;
    };
    interface HTMLSearchcraftInputLabelElement extends Components.SearchcraftInputLabel, HTMLStencilElement {
    }
    var HTMLSearchcraftInputLabelElement: {
        prototype: HTMLSearchcraftInputLabelElement;
        new (): HTMLSearchcraftInputLabelElement;
    };
    interface HTMLSearchcraftResultsInfoElement extends Components.SearchcraftResultsInfo, HTMLStencilElement {
    }
    var HTMLSearchcraftResultsInfoElement: {
        prototype: HTMLSearchcraftResultsInfoElement;
        new (): HTMLSearchcraftResultsInfoElement;
    };
    interface HTMLSearchcraftSearchIconSetElement extends Components.SearchcraftSearchIconSet, HTMLStencilElement {
    }
    var HTMLSearchcraftSearchIconSetElement: {
        prototype: HTMLSearchcraftSearchIconSetElement;
        new (): HTMLSearchcraftSearchIconSetElement;
    };
    interface HTMLSearchcraftSliderElementEventMap {
        "rangeChanged": { startValue: number; endValue: number };
    }
    interface HTMLSearchcraftSliderElement extends Components.SearchcraftSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftSliderElementEventMap>(type: K, listener: (this: HTMLSearchcraftSliderElement, ev: SearchcraftSliderCustomEvent<HTMLSearchcraftSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftSliderElementEventMap>(type: K, listener: (this: HTMLSearchcraftSliderElement, ev: SearchcraftSliderCustomEvent<HTMLSearchcraftSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftSliderElement: {
        prototype: HTMLSearchcraftSliderElement;
        new (): HTMLSearchcraftSliderElement;
    };
    interface HTMLSearchcraftSpinnerDarkElement extends Components.SearchcraftSpinnerDark, HTMLStencilElement {
    }
    var HTMLSearchcraftSpinnerDarkElement: {
        prototype: HTMLSearchcraftSpinnerDarkElement;
        new (): HTMLSearchcraftSpinnerDarkElement;
    };
    interface HTMLSearchcraftSpinnerLightElement extends Components.SearchcraftSpinnerLight, HTMLStencilElement {
    }
    var HTMLSearchcraftSpinnerLightElement: {
        prototype: HTMLSearchcraftSpinnerLightElement;
        new (): HTMLSearchcraftSpinnerLightElement;
    };
    interface HTMLSearchcraftToggleButtonElementEventMap {
        "toggleUpdated": boolean;
    }
    interface HTMLSearchcraftToggleButtonElement extends Components.SearchcraftToggleButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchcraftToggleButtonElementEventMap>(type: K, listener: (this: HTMLSearchcraftToggleButtonElement, ev: SearchcraftToggleButtonCustomEvent<HTMLSearchcraftToggleButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchcraftToggleButtonElementEventMap>(type: K, listener: (this: HTMLSearchcraftToggleButtonElement, ev: SearchcraftToggleButtonCustomEvent<HTMLSearchcraftToggleButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchcraftToggleButtonElement: {
        prototype: HTMLSearchcraftToggleButtonElement;
        new (): HTMLSearchcraftToggleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "searchcraft-auto-search-form": HTMLSearchcraftAutoSearchFormElement;
        "searchcraft-base-search-form": HTMLSearchcraftBaseSearchFormElement;
        "searchcraft-base-search-result": HTMLSearchcraftBaseSearchResultElement;
        "searchcraft-base-search-results": HTMLSearchcraftBaseSearchResultsElement;
        "searchcraft-button": HTMLSearchcraftButtonElement;
        "searchcraft-button-icon": HTMLSearchcraftButtonIconElement;
        "searchcraft-check-icon": HTMLSearchcraftCheckIconElement;
        "searchcraft-clear-icon-set": HTMLSearchcraftClearIconSetElement;
        "searchcraft-dash-icon": HTMLSearchcraftDashIconElement;
        "searchcraft-error-message": HTMLSearchcraftErrorMessageElement;
        "searchcraft-facet-list": HTMLSearchcraftFacetListElement;
        "searchcraft-filter-panel": HTMLSearchcraftFilterPanelElement;
        "searchcraft-input": HTMLSearchcraftInputElement;
        "searchcraft-input-label": HTMLSearchcraftInputLabelElement;
        "searchcraft-results-info": HTMLSearchcraftResultsInfoElement;
        "searchcraft-search-icon-set": HTMLSearchcraftSearchIconSetElement;
        "searchcraft-slider": HTMLSearchcraftSliderElement;
        "searchcraft-spinner-dark": HTMLSearchcraftSpinnerDarkElement;
        "searchcraft-spinner-light": HTMLSearchcraftSpinnerLightElement;
        "searchcraft-toggle-button": HTMLSearchcraftToggleButtonElement;
    }
}
declare namespace LocalJSX {
    interface SearchcraftAutoSearchForm {
        "autoSearchFormClass"?: string;
        "clearInput"?: () => void;
        "config"?: SearchcraftConfig;
        "customStylesForInput"?: string | Record<string, string>;
        "inputCaptionValue"?: string;
        "labelForInput"?: string;
        "onInputClearedOrNoResults"?: (event: SearchcraftAutoSearchFormCustomEvent<void>) => void;
        "onQuerySubmit"?: (event: SearchcraftAutoSearchFormCustomEvent<string>) => void;
        "placeholderValue"?: string;
        "searchContainerClass"?: string;
    }
    interface SearchcraftBaseSearchForm {
        "buttonLabel"?: string;
        "buttonPlacement"?: 'right' | 'left';
        "config"?: SearchcraftConfig;
        "errorMessage"?: string;
        "inputLabel"?: string;
        "onClearInput"?: (event: SearchcraftBaseSearchFormCustomEvent<any>) => void;
    }
    interface SearchcraftBaseSearchResult {
        "bodyContent"?: string | undefined;
        "buttonHref"?: string | undefined;
        "buttonLabel"?: string | undefined;
        "buttonRel"?: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "buttonTarget"?: '_blank' | '_self' | '_top' | '_parent';
        "containerHref"?: string | undefined;
        "containerRel"?: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "containerTarget"?: '_blank' | '_self' | '_top' | '_parent';
        "customStyles"?: string | undefined;
        "documentPosition"?: number;
        "footerContent"?: string | undefined;
        "imageAlt"?: string | undefined;
        "imagePlacement"?: 'left' | 'right';
        "imageSrc"?: string | undefined;
        "subtitleContent"?: string | undefined;
        "titleContent"?: string | undefined;
    }
    interface SearchcraftBaseSearchResults {
        "adInterval"?: number;
        "buttonLabel"?: string | undefined;
        "buttonRel"?: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "buttonTarget"?: '_blank' | '_self' | '_top' | '_parent';
        "containerHref"?: string | undefined;
        "containerRel"?: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
        "containerTarget"?: '_blank' | '_self' | '_top' | '_parent';
        "customStylesForResults"?: | string
    | Record<string, Record<string, string>>
    | undefined;
        "onNoResults"?: (event: SearchcraftBaseSearchResultsCustomEvent<void>) => void;
        "placeAdAtEnd"?: boolean;
        "placeAdAtStart"?: boolean;
        "resultImagePlacement"?: 'left' | 'right';
        "searchResultMappings"?: string | undefined;
    }
    interface SearchcraftButton {
        "iconElement"?: Element;
        "iconOnly"?: boolean;
        "iconPosition"?: string;
        "label"?: string;
        "onButtonClick"?: (event: SearchcraftButtonCustomEvent<void>) => void;
    }
    interface SearchcraftButtonIcon {
    }
    interface SearchcraftCheckIcon {
    }
    interface SearchcraftClearIconSet {
        /**
          * Type of the icon to display. Options: 'clear-light', 'clear-dark', 'arrow-light', 'arrow-dark'
         */
        "type"?: 'clear-light' | 'clear-dark' | 'arrow-light' | 'arrow-dark';
    }
    interface SearchcraftDashIcon {
    }
    interface SearchcraftErrorMessage {
        "errorMessage"?: string;
    }
    interface SearchcraftFacetList {
        "fieldName"?: string;
        "onFacetSelectionUpdated"?: (event: SearchcraftFacetListCustomEvent<{ paths: string[] }>) => void;
    }
    interface SearchcraftFilterPanel {
        "items"?: string | undefined;
    }
    interface SearchcraftInput {
        "customStyles"?: string | Record<string, string>;
        "error"?: boolean;
        "flex"?: boolean;
        "inputCaptionClassName"?: string;
        "inputCaptionValue"?: string;
        "inputClassName"?: string;
        "isRequesting"?: boolean;
        "onClearInput"?: (event: SearchcraftInputCustomEvent<void>) => void;
        "onInputChange"?: (event: SearchcraftInputCustomEvent<string>) => void;
        "placeholderValue"?: string;
        "query"?: string;
    }
    interface SearchcraftInputLabel {
        "inputLabelClassName"?: string;
        "label"?: string;
    }
    interface SearchcraftResultsInfo {
    }
    interface SearchcraftSearchIconSet {
        "height"?: number;
        /**
          * Type of the icon to display. Options: 'search-light', 'search-dark', 'error-light', 'error-dark'
         */
        "type"?: 'search-light' | 'search-dark' | 'error-light' | 'error-dark';
        "width"?: number;
    }
    interface SearchcraftSlider {
        "dataType"?: 'number' | 'date';
        "granularity"?: number;
        "max"?: number;
        "min"?: number;
        "onRangeChanged"?: (event: SearchcraftSliderCustomEvent<{ startValue: number; endValue: number }>) => void;
    }
    interface SearchcraftSpinnerDark {
    }
    interface SearchcraftSpinnerLight {
    }
    interface SearchcraftToggleButton {
        /**
          * Type of the toggle - determines what it controls 'mode': toggles between 'fuzzy' and 'normal' 'sort': toggles between 'asc' and 'desc'
         */
        "label"?: string;
        "onToggleUpdated"?: (event: SearchcraftToggleButtonCustomEvent<boolean>) => void;
        "subLabel"?: string | undefined;
    }
    interface IntrinsicElements {
        "searchcraft-auto-search-form": SearchcraftAutoSearchForm;
        "searchcraft-base-search-form": SearchcraftBaseSearchForm;
        "searchcraft-base-search-result": SearchcraftBaseSearchResult;
        "searchcraft-base-search-results": SearchcraftBaseSearchResults;
        "searchcraft-button": SearchcraftButton;
        "searchcraft-button-icon": SearchcraftButtonIcon;
        "searchcraft-check-icon": SearchcraftCheckIcon;
        "searchcraft-clear-icon-set": SearchcraftClearIconSet;
        "searchcraft-dash-icon": SearchcraftDashIcon;
        "searchcraft-error-message": SearchcraftErrorMessage;
        "searchcraft-facet-list": SearchcraftFacetList;
        "searchcraft-filter-panel": SearchcraftFilterPanel;
        "searchcraft-input": SearchcraftInput;
        "searchcraft-input-label": SearchcraftInputLabel;
        "searchcraft-results-info": SearchcraftResultsInfo;
        "searchcraft-search-icon-set": SearchcraftSearchIconSet;
        "searchcraft-slider": SearchcraftSlider;
        "searchcraft-spinner-dark": SearchcraftSpinnerDark;
        "searchcraft-spinner-light": SearchcraftSpinnerLight;
        "searchcraft-toggle-button": SearchcraftToggleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "searchcraft-auto-search-form": LocalJSX.SearchcraftAutoSearchForm & JSXBase.HTMLAttributes<HTMLSearchcraftAutoSearchFormElement>;
            "searchcraft-base-search-form": LocalJSX.SearchcraftBaseSearchForm & JSXBase.HTMLAttributes<HTMLSearchcraftBaseSearchFormElement>;
            "searchcraft-base-search-result": LocalJSX.SearchcraftBaseSearchResult & JSXBase.HTMLAttributes<HTMLSearchcraftBaseSearchResultElement>;
            "searchcraft-base-search-results": LocalJSX.SearchcraftBaseSearchResults & JSXBase.HTMLAttributes<HTMLSearchcraftBaseSearchResultsElement>;
            "searchcraft-button": LocalJSX.SearchcraftButton & JSXBase.HTMLAttributes<HTMLSearchcraftButtonElement>;
            "searchcraft-button-icon": LocalJSX.SearchcraftButtonIcon & JSXBase.HTMLAttributes<HTMLSearchcraftButtonIconElement>;
            "searchcraft-check-icon": LocalJSX.SearchcraftCheckIcon & JSXBase.HTMLAttributes<HTMLSearchcraftCheckIconElement>;
            "searchcraft-clear-icon-set": LocalJSX.SearchcraftClearIconSet & JSXBase.HTMLAttributes<HTMLSearchcraftClearIconSetElement>;
            "searchcraft-dash-icon": LocalJSX.SearchcraftDashIcon & JSXBase.HTMLAttributes<HTMLSearchcraftDashIconElement>;
            "searchcraft-error-message": LocalJSX.SearchcraftErrorMessage & JSXBase.HTMLAttributes<HTMLSearchcraftErrorMessageElement>;
            "searchcraft-facet-list": LocalJSX.SearchcraftFacetList & JSXBase.HTMLAttributes<HTMLSearchcraftFacetListElement>;
            "searchcraft-filter-panel": LocalJSX.SearchcraftFilterPanel & JSXBase.HTMLAttributes<HTMLSearchcraftFilterPanelElement>;
            "searchcraft-input": LocalJSX.SearchcraftInput & JSXBase.HTMLAttributes<HTMLSearchcraftInputElement>;
            "searchcraft-input-label": LocalJSX.SearchcraftInputLabel & JSXBase.HTMLAttributes<HTMLSearchcraftInputLabelElement>;
            "searchcraft-results-info": LocalJSX.SearchcraftResultsInfo & JSXBase.HTMLAttributes<HTMLSearchcraftResultsInfoElement>;
            "searchcraft-search-icon-set": LocalJSX.SearchcraftSearchIconSet & JSXBase.HTMLAttributes<HTMLSearchcraftSearchIconSetElement>;
            "searchcraft-slider": LocalJSX.SearchcraftSlider & JSXBase.HTMLAttributes<HTMLSearchcraftSliderElement>;
            "searchcraft-spinner-dark": LocalJSX.SearchcraftSpinnerDark & JSXBase.HTMLAttributes<HTMLSearchcraftSpinnerDarkElement>;
            "searchcraft-spinner-light": LocalJSX.SearchcraftSpinnerLight & JSXBase.HTMLAttributes<HTMLSearchcraftSpinnerLightElement>;
            "searchcraft-toggle-button": LocalJSX.SearchcraftToggleButton & JSXBase.HTMLAttributes<HTMLSearchcraftToggleButtonElement>;
        }
    }
}
